import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import { useEffect } from 'react'
import { db, auth } from '../firebase'
import { useAuthState } from 'react-firebase-hooks/auth'

export default function Home() {
  const [user] = useAuthState(auth)
  const userRef = db.collection('users').doc(user.uid)

  useEffect(() => {
    userRef.set({ chatWith: '' }, { merge: true })
  }, [])

  return (
    <div>
      <Head>
        <title>Whatsapp Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Sidebar />
    </div>
  )
}
